name: first_flutter_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.10.8
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  flutter_blue_plus: ^1.35.4
  file_picker: ^8.0.6
  permission_handler: ^11.3.1
  mqtt_client: ^10.11.10
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
