// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASizWJ6TJihpxuBKpFCZFkAB3JRuh7q7A',
    appId: '1:123455912744:web:4dcf2f20f6cf32f4572e1d',
    messagingSenderId: '123455912744',
    projectId: 'datn-2026-86599',
    authDomain: 'datn-2026-86599.firebaseapp.com',
    databaseURL: 'https://datn-2026-86599-default-rtdb.firebaseio.com',
    storageBucket: 'datn-2026-86599.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeOGFZ-NeUB5D1-0yepV7ZanNaSFX0lQ',
    appId: '1:123455912744:android:e0e06e4bae5c99ae572e1d',
    messagingSenderId: '123455912744',
    projectId: 'datn-2026-86599',
    databaseURL: 'https://datn-2026-86599-default-rtdb.firebaseio.com',
    storageBucket: 'datn-2026-86599.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nLbHg4cOuLOVQ0YlNR9oLJCqXC9tESM',
    appId: '1:123455912744:ios:9d11e38eaebfce33572e1d',
    messagingSenderId: '123455912744',
    projectId: 'datn-2026-86599',
    databaseURL: 'https://datn-2026-86599-default-rtdb.firebaseio.com',
    storageBucket: 'datn-2026-86599.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nLbHg4cOuLOVQ0YlNR9oLJCqXC9tESM',
    appId: '1:123455912744:ios:9d11e38eaebfce33572e1d',
    messagingSenderId: '123455912744',
    projectId: 'datn-2026-86599',
    databaseURL: 'https://datn-2026-86599-default-rtdb.firebaseio.com',
    storageBucket: 'datn-2026-86599.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASizWJ6TJihpxuBKpFCZFkAB3JRuh7q7A',
    appId: '1:123455912744:web:f3ab228fa8d52382572e1d',
    messagingSenderId: '123455912744',
    projectId: 'datn-2026-86599',
    authDomain: 'datn-2026-86599.firebaseapp.com',
    databaseURL: 'https://datn-2026-86599-default-rtdb.firebaseio.com',
    storageBucket: 'datn-2026-86599.firebasestorage.app',
  );
}
